version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    network_mode: "host"
    volumes:
      - db-data:/var/lib/mysql/data
    ports:
      - 3306:3306
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: access-api
    environment:
      - MYSQL_HOST=db
      - PORT=3306
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
       - db  
    network_mode: "host" 
    links:
      - 'db:database'
volumes:
  db-data:
    driver: local