version: '3.8'

services:
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: access
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/QUINIELAS?jdbcCompliantTruncation=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    links:
      - 'db:database'
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    expose:
      - "3306"
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - ./cache/mysql:/var/lib/mysql
      - ./conf-mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped