version: '3.8'

services: 
  api:
    container_name: access
    build:
      context: ./
      target: dev
    image: access-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: dev
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: QUINIELAS
    links:
      - db
    volumes:
      - ./:/src      
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=QUINIELAS
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
    driver: local