version: '3'

services:
  app:
    image: app:latest
    ports:
       - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/QUINIELAS?jdbcCompliantTruncation=false
    depends_on:
       - mysql