version: '3.8'

services:
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: access-api
    environment:
      - MYSQL_HOST=db
      - PORT=5432
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      quinieslas-network:  
    links:
      - 'db:database'
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      quinieslas-network:  
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local