supportMail: mariohdzglez@gmail.com
AESFront: chesco0000000000
AESDecryptBack : Chofis12
AESEncryptBack : Betza20


spring:
  jpa:
    hibernate.ddl-auto: update 
    generate-ddl: true
    show-sql: true
server:
  servlet:
    context-path: /accesos/api
  error:
    include-stacktrace: never
    
        
    
    