supportMail: mariohdzglez@gmail.com
AESFront: chesco0000000000
AESDecryptBack : Chofis12
AESEncryptBack : Betza20


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3006}/QUINIELAS?jdbcCompliantTruncation=false 
  jpa:
    hibernate.ddl-auto: update 
    generate-ddl: true
    show-sql: true
server:
  servlet:
    context-path: /accesos/api
  error:
    include-stacktrace: never