supportMail: mariohdzglez@gmail.com
AESFront: chesco0000000000
AESDecryptBack : Chofis12
AESEncryptBack : Betza20

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    url:  ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/QUINIELAS?jdbcCompliantTruncation=false}    
  jpa:
    hibernate.ddl-auto: update 
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  
server:
  servlet:
    context-path: /accesos/api
  error:
    include-stacktrace: never
    
        
    
    