spring:
  profiles:
    active: docker
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    
    url: jdbc:mysql://mysql:3306/QUINIELAS?jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update 
    generate-ddl: true
    show-sql: true
server:
  servlet:
    context-path: /accesos/api
  error:
    include-stacktrace: never
    